pull_request_rules:
  - name: automatic merge for master
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - label!=work-in-progress
    - '#approved-reviews-by>=1'
    - status-success=Travis CI - Pull Request
    - base=master
  - name: automatic merge for stable branches
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true    
    conditions:
    - label!=work-in-progress
    - '#approved-reviews-by>=1'
    - status-success=continuous-integration/travis-ci/pr
    - base~=^stable/
