name: python-gnocchiclient

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      matrix:
        env:
          - docs-gnocchi-web
          - pep8
          - py36
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: ./tools/install_deps.sh
      - name: Run tox
        run: tox -e ${{ matrix.env }}
